'use client'

import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'

interface TermsModalProps {
  open: boolean
  onOpenChange: (open: boolean) => void
}

export function TermsModal({ open, onOpenChange }: TermsModalProps) {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-h-[80vh] overflow-y-auto sm:max-w-xl">
        <DialogHeader>
          <DialogTitle>Terms of Use</DialogTitle>
        </DialogHeader>

        <div className="space-y-4 text-sm text-muted-foreground leading-relaxed">
          <p><strong className="text-foreground">Last Updated:</strong> March 6, 2026</p>

          <section>
            <h3 className="font-semibold text-foreground">1. Acceptance of Terms</h3>
            <p>
              By accessing and using NutriSnap (&quot;the Service&quot;), you accept and agree to be bound by the terms and provision of this agreement.
            </p>
          </section>

          <section>
            <h3 className="font-semibold text-foreground">2. Description of Service</h3>
            <p>
              NutriSnap provides AI-powered meal analysis and nutritional tracking. The dietary information, macronutrient breakdowns, and health tracking features provided by the Service are generated by artificial intelligence and are for informational and educational purposes only.
            </p>
          </section>

          <section>
            <h3 className="font-semibold text-foreground">3. Medical Disclaimer</h3>
            <p>
              NutriSnap is not a medical application. The information provided by the Service is not a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician, a registered dietitian, or other health provider with any questions you may have regarding a medical condition or dietary restrictions.
            </p>
          </section>

          <section>
            <h3 className="font-semibold text-foreground">4. User Accounts and Data</h3>
            <p>
              To use certain features, you must create an account. You are responsible for maintaining the confidentiality of your account information. By uploading images of meals to the Service, you grant NutriSnap permission to process these images through third-party AI services solely for the purpose of providing nutritional analysis.
            </p>
          </section>

          <section>
            <h3 className="font-semibold text-foreground">5. Limitation of Liability</h3>
            <p>
              The Service is provided on an &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; basis. As a developer project, we make no guarantees regarding the continuous availability or absolute accuracy of the AI-generated nutritional data. In no event shall NutriSnap, its developer, or affiliates be liable for any indirect, incidental, special, or consequential damages arising from the use of the Service.
            </p>
          </section>
        </div>

        <div className="mt-2 flex justify-end">
          <Button type="button" variant="outline" onClick={() => onOpenChange(false)}>
            Close
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  )
}
