'use client'

import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'

interface TermsModalProps {
  open: boolean
  onOpenChange: (open: boolean) => void
}

export function TermsModal({ open, onOpenChange }: TermsModalProps) {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-h-[80vh] overflow-y-auto sm:max-w-xl">
        <DialogHeader>
          <DialogTitle>Terms of Service & Privacy Policy</DialogTitle>
        </DialogHeader>

        <div className="space-y-4 text-sm text-muted-foreground leading-relaxed">
          <p><strong className="text-foreground">Last Updated:</strong> March 6, 2026</p>

          <section>
            <h3 className="font-semibold text-foreground">Acceptance of Terms</h3>
            <p>
              By accessing and using this application, you accept and agree to be bound by the terms and provision of this agreement.
            </p>
          </section>

          <section>
            <h3 className="font-semibold text-foreground">Description of Service</h3>
            <p>
              NutriSnap provides AI-powered nutritional analysis of food images. Calorie counts and macro estimates are approximations generated by AI and may not be 100% accurate.
            </p>
          </section>

          <section>
            <h3 className="font-semibold text-foreground">Medical Disclaimer</h3>
            <p>
              This app does not provide medical advice. It is intended for informational purposes only. Always consult a qualified healthcare provider regarding dietary changes or health conditions.
            </p>
          </section>

          <section>
            <h3 className="font-semibold text-foreground">Data & Privacy</h3>
            <p>
              We protect your personal information. Only images voluntarily uploaded will be analyzed. We do not sell your personal data to third parties.
            </p>
          </section>

          <section>
            <h3 className="font-semibold text-foreground">Limitation of Liability</h3>
            <p>
              We shall not be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use the service.
            </p>
          </section>
        </div>

        <div className="mt-2 flex justify-end">
          <Button type="button" variant="outline" onClick={() => onOpenChange(false)}>
            Close
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  )
}
